### ISSUE TITLE
Palette and Colours

### ISSUE THREAD

**Issue by luserx0** [luserx0/opinionated-bits-blog#24]
Decision on Blog's pallet and specific colours to be used

**Comment by An0u** [comment]
Working on implementing/testing these palletes.
Dark Theme:
- #fc3753 --pink - highkights
- #2823c5 -- grey/black
- #97ff10 -- green text-bold
-#white -- text

White Theme:
- #black -- text
- #97ff10 -- green text-bold
- #white -- background

**Comment by luserx0** [comment]
Nice. We roll with these and adjust upon demand

**Comment by luserx0** [comment]
Resolved by 3c0da1e3b2935cf86202014d7121eb523e183380
